/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yadlings.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StockVolume extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1886153210073658492L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockVolume\",\"namespace\":\"com.yadlings.avro\",\"fields\":[{\"name\":\"symbol\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"industry\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"shares\",\"type\":\"int\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StockVolume> ENCODER =
      new BinaryMessageEncoder<StockVolume>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockVolume> DECODER =
      new BinaryMessageDecoder<StockVolume>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StockVolume> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StockVolume> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StockVolume> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StockVolume>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StockVolume to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StockVolume from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StockVolume instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StockVolume fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence symbol;
   private java.lang.CharSequence industry;
   private int shares;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockVolume() {}

  /**
   * All-args constructor.
   * @param symbol The new value for symbol
   * @param industry The new value for industry
   * @param shares The new value for shares
   */
  public StockVolume(java.lang.CharSequence symbol, java.lang.CharSequence industry, java.lang.Integer shares) {
    this.symbol = symbol;
    this.industry = industry;
    this.shares = shares;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return symbol;
    case 1: return industry;
    case 2: return shares;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: symbol = (java.lang.CharSequence)value$; break;
    case 1: industry = (java.lang.CharSequence)value$; break;
    case 2: shares = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'symbol' field.
   * @return The value of the 'symbol' field.
   */
  public java.lang.CharSequence getSymbol() {
    return symbol;
  }


  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.CharSequence value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'industry' field.
   * @return The value of the 'industry' field.
   */
  public java.lang.CharSequence getIndustry() {
    return industry;
  }


  /**
   * Sets the value of the 'industry' field.
   * @param value the value to set.
   */
  public void setIndustry(java.lang.CharSequence value) {
    this.industry = value;
  }

  /**
   * Gets the value of the 'shares' field.
   * @return The value of the 'shares' field.
   */
  public int getShares() {
    return shares;
  }


  /**
   * Sets the value of the 'shares' field.
   * @param value the value to set.
   */
  public void setShares(int value) {
    this.shares = value;
  }

  /**
   * Creates a new StockVolume RecordBuilder.
   * @return A new StockVolume RecordBuilder
   */
  public static com.yadlings.avro.StockVolume.Builder newBuilder() {
    return new com.yadlings.avro.StockVolume.Builder();
  }

  /**
   * Creates a new StockVolume RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockVolume RecordBuilder
   */
  public static com.yadlings.avro.StockVolume.Builder newBuilder(com.yadlings.avro.StockVolume.Builder other) {
    if (other == null) {
      return new com.yadlings.avro.StockVolume.Builder();
    } else {
      return new com.yadlings.avro.StockVolume.Builder(other);
    }
  }

  /**
   * Creates a new StockVolume RecordBuilder by copying an existing StockVolume instance.
   * @param other The existing instance to copy.
   * @return A new StockVolume RecordBuilder
   */
  public static com.yadlings.avro.StockVolume.Builder newBuilder(com.yadlings.avro.StockVolume other) {
    if (other == null) {
      return new com.yadlings.avro.StockVolume.Builder();
    } else {
      return new com.yadlings.avro.StockVolume.Builder(other);
    }
  }

  /**
   * RecordBuilder for StockVolume instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockVolume>
    implements org.apache.avro.data.RecordBuilder<StockVolume> {

    private java.lang.CharSequence symbol;
    private java.lang.CharSequence industry;
    private int shares;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yadlings.avro.StockVolume.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.industry)) {
        this.industry = data().deepCopy(fields()[1].schema(), other.industry);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.shares)) {
        this.shares = data().deepCopy(fields()[2].schema(), other.shares);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing StockVolume instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yadlings.avro.StockVolume other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.industry)) {
        this.industry = data().deepCopy(fields()[1].schema(), other.industry);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.shares)) {
        this.shares = data().deepCopy(fields()[2].schema(), other.shares);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'symbol' field.
      * @return The value.
      */
    public java.lang.CharSequence getSymbol() {
      return symbol;
    }


    /**
      * Sets the value of the 'symbol' field.
      * @param value The value of 'symbol'.
      * @return This builder.
      */
    public com.yadlings.avro.StockVolume.Builder setSymbol(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.symbol = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'symbol' field has been set.
      * @return True if the 'symbol' field has been set, false otherwise.
      */
    public boolean hasSymbol() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'symbol' field.
      * @return This builder.
      */
    public com.yadlings.avro.StockVolume.Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'industry' field.
      * @return The value.
      */
    public java.lang.CharSequence getIndustry() {
      return industry;
    }


    /**
      * Sets the value of the 'industry' field.
      * @param value The value of 'industry'.
      * @return This builder.
      */
    public com.yadlings.avro.StockVolume.Builder setIndustry(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.industry = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'industry' field has been set.
      * @return True if the 'industry' field has been set, false otherwise.
      */
    public boolean hasIndustry() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'industry' field.
      * @return This builder.
      */
    public com.yadlings.avro.StockVolume.Builder clearIndustry() {
      industry = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'shares' field.
      * @return The value.
      */
    public int getShares() {
      return shares;
    }


    /**
      * Sets the value of the 'shares' field.
      * @param value The value of 'shares'.
      * @return This builder.
      */
    public com.yadlings.avro.StockVolume.Builder setShares(int value) {
      validate(fields()[2], value);
      this.shares = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'shares' field has been set.
      * @return True if the 'shares' field has been set, false otherwise.
      */
    public boolean hasShares() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'shares' field.
      * @return This builder.
      */
    public com.yadlings.avro.StockVolume.Builder clearShares() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockVolume build() {
      try {
        StockVolume record = new StockVolume();
        record.symbol = fieldSetFlags()[0] ? this.symbol : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.industry = fieldSetFlags()[1] ? this.industry : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.shares = fieldSetFlags()[2] ? this.shares : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockVolume>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockVolume>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockVolume>
    READER$ = (org.apache.avro.io.DatumReader<StockVolume>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.symbol);

    out.writeString(this.industry);

    out.writeInt(this.shares);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.symbol = in.readString(this.symbol instanceof Utf8 ? (Utf8)this.symbol : null);

      this.industry = in.readString(this.industry instanceof Utf8 ? (Utf8)this.industry : null);

      this.shares = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.symbol = in.readString(this.symbol instanceof Utf8 ? (Utf8)this.symbol : null);
          break;

        case 1:
          this.industry = in.readString(this.industry instanceof Utf8 ? (Utf8)this.industry : null);
          break;

        case 2:
          this.shares = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










