state:
  rewardState: RewardState
  retention.ms: 604800000
  retention.byte: 10000000000
  cleanup.policy: compact
server:
  port: 8082
topic:
  discount: discount_0_0_0
  reward: reward_0_0_0
  bonus: Bonus_0_0_0
  main: Transactions_0_0_0
  maskTopic: MaskedTransactions_0_0_0
  storeone: FirstStore_0_0_0
  storetwo: SecondStore_0_0_0
  partitions: 3
  replicas: 3
  schema: http://10.33.121.148:8081
stockTopics:
  stockTransactions: StockTransactions_0_0_2
  stockVolume: stockVolume_0_0_0
  stockDelta: StockToDisplay_0_0_0
topologyTopics:
  upper: upper
  upper1: upper1
  lower: lower
userTopics:
  registered: RegisteringUsers_0_0_0
  user_admin: Adminusers_0_0_0
  user_local: LocalUsers_0_0_0
  user_count: UserCount_0_0_0
  countState: CountState_0_0_9
spring:
  application:
    name: stream-prcessor14
  kafka:
    streams:
      properties:
        cache.max.bytes.buffering: 10485760
        commit.interval.ms: 10000
#        metrics.recording.level: DEBUG
#        default.timestamp.extractor: com.yadlings.streamprocessor.Stock.TimeStampExtractor
    bootstrap-servers: 10.33.121.90:9090,10.33.121.90:9091,10.33.121.90:9092