/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yadlings.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SymbolShares extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6257619742477243438L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SymbolShares\",\"namespace\":\"com.yadlings.avro\",\"fields\":[{\"name\":\"symbol\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"total\",\"type\":\"int\",\"default\":0},{\"name\":\"numberOfSymbols\",\"type\":\"int\",\"default\":0},{\"name\":\"average\",\"type\":\"int\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SymbolShares> ENCODER =
      new BinaryMessageEncoder<SymbolShares>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SymbolShares> DECODER =
      new BinaryMessageDecoder<SymbolShares>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SymbolShares> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SymbolShares> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SymbolShares> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SymbolShares>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SymbolShares to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SymbolShares from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SymbolShares instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SymbolShares fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence symbol;
   private int total;
   private int numberOfSymbols;
   private int average;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SymbolShares() {}

  /**
   * All-args constructor.
   * @param symbol The new value for symbol
   * @param total The new value for total
   * @param numberOfSymbols The new value for numberOfSymbols
   * @param average The new value for average
   */
  public SymbolShares(java.lang.CharSequence symbol, java.lang.Integer total, java.lang.Integer numberOfSymbols, java.lang.Integer average) {
    this.symbol = symbol;
    this.total = total;
    this.numberOfSymbols = numberOfSymbols;
    this.average = average;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return symbol;
    case 1: return total;
    case 2: return numberOfSymbols;
    case 3: return average;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: symbol = (java.lang.CharSequence)value$; break;
    case 1: total = (java.lang.Integer)value$; break;
    case 2: numberOfSymbols = (java.lang.Integer)value$; break;
    case 3: average = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'symbol' field.
   * @return The value of the 'symbol' field.
   */
  public java.lang.CharSequence getSymbol() {
    return symbol;
  }


  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.CharSequence value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'total' field.
   * @return The value of the 'total' field.
   */
  public int getTotal() {
    return total;
  }


  /**
   * Sets the value of the 'total' field.
   * @param value the value to set.
   */
  public void setTotal(int value) {
    this.total = value;
  }

  /**
   * Gets the value of the 'numberOfSymbols' field.
   * @return The value of the 'numberOfSymbols' field.
   */
  public int getNumberOfSymbols() {
    return numberOfSymbols;
  }


  /**
   * Sets the value of the 'numberOfSymbols' field.
   * @param value the value to set.
   */
  public void setNumberOfSymbols(int value) {
    this.numberOfSymbols = value;
  }

  /**
   * Gets the value of the 'average' field.
   * @return The value of the 'average' field.
   */
  public int getAverage() {
    return average;
  }


  /**
   * Sets the value of the 'average' field.
   * @param value the value to set.
   */
  public void setAverage(int value) {
    this.average = value;
  }

  /**
   * Creates a new SymbolShares RecordBuilder.
   * @return A new SymbolShares RecordBuilder
   */
  public static com.yadlings.avro.SymbolShares.Builder newBuilder() {
    return new com.yadlings.avro.SymbolShares.Builder();
  }

  /**
   * Creates a new SymbolShares RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SymbolShares RecordBuilder
   */
  public static com.yadlings.avro.SymbolShares.Builder newBuilder(com.yadlings.avro.SymbolShares.Builder other) {
    if (other == null) {
      return new com.yadlings.avro.SymbolShares.Builder();
    } else {
      return new com.yadlings.avro.SymbolShares.Builder(other);
    }
  }

  /**
   * Creates a new SymbolShares RecordBuilder by copying an existing SymbolShares instance.
   * @param other The existing instance to copy.
   * @return A new SymbolShares RecordBuilder
   */
  public static com.yadlings.avro.SymbolShares.Builder newBuilder(com.yadlings.avro.SymbolShares other) {
    if (other == null) {
      return new com.yadlings.avro.SymbolShares.Builder();
    } else {
      return new com.yadlings.avro.SymbolShares.Builder(other);
    }
  }

  /**
   * RecordBuilder for SymbolShares instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SymbolShares>
    implements org.apache.avro.data.RecordBuilder<SymbolShares> {

    private java.lang.CharSequence symbol;
    private int total;
    private int numberOfSymbols;
    private int average;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yadlings.avro.SymbolShares.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.total)) {
        this.total = data().deepCopy(fields()[1].schema(), other.total);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.numberOfSymbols)) {
        this.numberOfSymbols = data().deepCopy(fields()[2].schema(), other.numberOfSymbols);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.average)) {
        this.average = data().deepCopy(fields()[3].schema(), other.average);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing SymbolShares instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yadlings.avro.SymbolShares other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.total)) {
        this.total = data().deepCopy(fields()[1].schema(), other.total);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numberOfSymbols)) {
        this.numberOfSymbols = data().deepCopy(fields()[2].schema(), other.numberOfSymbols);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.average)) {
        this.average = data().deepCopy(fields()[3].schema(), other.average);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'symbol' field.
      * @return The value.
      */
    public java.lang.CharSequence getSymbol() {
      return symbol;
    }


    /**
      * Sets the value of the 'symbol' field.
      * @param value The value of 'symbol'.
      * @return This builder.
      */
    public com.yadlings.avro.SymbolShares.Builder setSymbol(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.symbol = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'symbol' field has been set.
      * @return True if the 'symbol' field has been set, false otherwise.
      */
    public boolean hasSymbol() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'symbol' field.
      * @return This builder.
      */
    public com.yadlings.avro.SymbolShares.Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'total' field.
      * @return The value.
      */
    public int getTotal() {
      return total;
    }


    /**
      * Sets the value of the 'total' field.
      * @param value The value of 'total'.
      * @return This builder.
      */
    public com.yadlings.avro.SymbolShares.Builder setTotal(int value) {
      validate(fields()[1], value);
      this.total = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'total' field has been set.
      * @return True if the 'total' field has been set, false otherwise.
      */
    public boolean hasTotal() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'total' field.
      * @return This builder.
      */
    public com.yadlings.avro.SymbolShares.Builder clearTotal() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'numberOfSymbols' field.
      * @return The value.
      */
    public int getNumberOfSymbols() {
      return numberOfSymbols;
    }


    /**
      * Sets the value of the 'numberOfSymbols' field.
      * @param value The value of 'numberOfSymbols'.
      * @return This builder.
      */
    public com.yadlings.avro.SymbolShares.Builder setNumberOfSymbols(int value) {
      validate(fields()[2], value);
      this.numberOfSymbols = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'numberOfSymbols' field has been set.
      * @return True if the 'numberOfSymbols' field has been set, false otherwise.
      */
    public boolean hasNumberOfSymbols() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'numberOfSymbols' field.
      * @return This builder.
      */
    public com.yadlings.avro.SymbolShares.Builder clearNumberOfSymbols() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'average' field.
      * @return The value.
      */
    public int getAverage() {
      return average;
    }


    /**
      * Sets the value of the 'average' field.
      * @param value The value of 'average'.
      * @return This builder.
      */
    public com.yadlings.avro.SymbolShares.Builder setAverage(int value) {
      validate(fields()[3], value);
      this.average = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'average' field has been set.
      * @return True if the 'average' field has been set, false otherwise.
      */
    public boolean hasAverage() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'average' field.
      * @return This builder.
      */
    public com.yadlings.avro.SymbolShares.Builder clearAverage() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SymbolShares build() {
      try {
        SymbolShares record = new SymbolShares();
        record.symbol = fieldSetFlags()[0] ? this.symbol : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.total = fieldSetFlags()[1] ? this.total : (java.lang.Integer) defaultValue(fields()[1]);
        record.numberOfSymbols = fieldSetFlags()[2] ? this.numberOfSymbols : (java.lang.Integer) defaultValue(fields()[2]);
        record.average = fieldSetFlags()[3] ? this.average : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SymbolShares>
    WRITER$ = (org.apache.avro.io.DatumWriter<SymbolShares>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SymbolShares>
    READER$ = (org.apache.avro.io.DatumReader<SymbolShares>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.symbol);

    out.writeInt(this.total);

    out.writeInt(this.numberOfSymbols);

    out.writeInt(this.average);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.symbol = in.readString(this.symbol instanceof Utf8 ? (Utf8)this.symbol : null);

      this.total = in.readInt();

      this.numberOfSymbols = in.readInt();

      this.average = in.readInt();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.symbol = in.readString(this.symbol instanceof Utf8 ? (Utf8)this.symbol : null);
          break;

        case 1:
          this.total = in.readInt();
          break;

        case 2:
          this.numberOfSymbols = in.readInt();
          break;

        case 3:
          this.average = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










