/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yadlings.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

import java.util.Comparator;

@org.apache.avro.specific.AvroGenerated
public class Top extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2310459214377466459L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Top\",\"namespace\":\"com.yadlings.avro\",\"fields\":[{\"name\":\"top\",\"type\":\"int\",\"default\":0},{\"name\":\"topShares\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"StockVolume\",\"fields\":[{\"name\":\"symbol\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"industry\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"shares\",\"type\":\"int\",\"default\":0}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Top> ENCODER =
      new BinaryMessageEncoder<Top>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Top> DECODER =
      new BinaryMessageDecoder<Top>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Top> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Top> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Top> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Top>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Top to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Top from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Top instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Top fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int top;
   private java.util.List<com.yadlings.avro.StockVolume> topShares;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Top() {}

  /**
   * All-args constructor.
   * @param top The new value for top
   * @param topShares The new value for topShares
   */
  public Top(java.lang.Integer top, java.util.List<com.yadlings.avro.StockVolume> topShares) {
    this.top = top;
    this.topShares = topShares;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return top;
    case 1: return topShares;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: top = (java.lang.Integer)value$; break;
    case 1: topShares = (java.util.List<com.yadlings.avro.StockVolume>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'top' field.
   * @return The value of the 'top' field.
   */
  public int getTop() {
    return top;
  }


  /**
   * Sets the value of the 'top' field.
   * @param value the value to set.
   */
  public void setTop(int value) {
    this.top = value;
  }

  /**
   * Gets the value of the 'topShares' field.
   * @return The value of the 'topShares' field.
   */
  public java.util.List<com.yadlings.avro.StockVolume> getTopShares() {
    return topShares;
  }


  /**
   * Sets the value of the 'topShares' field.
   * @param value the value to set.
   */
  public void setTopShares(java.util.List<com.yadlings.avro.StockVolume> value) {
    this.topShares = value;
  }
  public Top addTopShares(com.yadlings.avro.StockVolume value) {
    Comparator<com.yadlings.avro.StockVolume> comparator = (value1,value2) -> value2.getShares()-value1.getShares();
    this.topShares.add(value);
    this.topShares.sort(comparator);
    if (this.topShares.size()>this.top) this.topShares.remove(this.top);
    return this;
  }
  public Top removeTopShares(com.yadlings.avro.StockVolume value) {
    int index = this.topShares.indexOf(value);
    if(index>-1) this.topShares.remove(index);
    return this;
  }
  /**
   * Creates a new Top RecordBuilder.
   * @return A new Top RecordBuilder
   */
  public static com.yadlings.avro.Top.Builder newBuilder() {
    return new com.yadlings.avro.Top.Builder();
  }

  /**
   * Creates a new Top RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Top RecordBuilder
   */
  public static com.yadlings.avro.Top.Builder newBuilder(com.yadlings.avro.Top.Builder other) {
    if (other == null) {
      return new com.yadlings.avro.Top.Builder();
    } else {
      return new com.yadlings.avro.Top.Builder(other);
    }
  }

  /**
   * Creates a new Top RecordBuilder by copying an existing Top instance.
   * @param other The existing instance to copy.
   * @return A new Top RecordBuilder
   */
  public static com.yadlings.avro.Top.Builder newBuilder(com.yadlings.avro.Top other) {
    if (other == null) {
      return new com.yadlings.avro.Top.Builder();
    } else {
      return new com.yadlings.avro.Top.Builder(other);
    }
  }

  /**
   * RecordBuilder for Top instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Top>
    implements org.apache.avro.data.RecordBuilder<Top> {

    private int top;
    private java.util.List<com.yadlings.avro.StockVolume> topShares;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yadlings.avro.Top.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.top)) {
        this.top = data().deepCopy(fields()[0].schema(), other.top);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.topShares)) {
        this.topShares = data().deepCopy(fields()[1].schema(), other.topShares);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Top instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yadlings.avro.Top other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.top)) {
        this.top = data().deepCopy(fields()[0].schema(), other.top);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.topShares)) {
        this.topShares = data().deepCopy(fields()[1].schema(), other.topShares);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'top' field.
      * @return The value.
      */
    public int getTop() {
      return top;
    }


    /**
      * Sets the value of the 'top' field.
      * @param value The value of 'top'.
      * @return This builder.
      */
    public com.yadlings.avro.Top.Builder setTop(int value) {
      validate(fields()[0], value);
      this.top = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'top' field has been set.
      * @return True if the 'top' field has been set, false otherwise.
      */
    public boolean hasTop() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'top' field.
      * @return This builder.
      */
    public com.yadlings.avro.Top.Builder clearTop() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'topShares' field.
      * @return The value.
      */
    public java.util.List<com.yadlings.avro.StockVolume> getTopShares() {
      return topShares;
    }


    /**
      * Sets the value of the 'topShares' field.
      * @param value The value of 'topShares'.
      * @return This builder.
      */
    public com.yadlings.avro.Top.Builder setTopShares(java.util.List<com.yadlings.avro.StockVolume> value) {
      validate(fields()[1], value);
      this.topShares = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'topShares' field has been set.
      * @return True if the 'topShares' field has been set, false otherwise.
      */
    public boolean hasTopShares() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'topShares' field.
      * @return This builder.
      */
    public com.yadlings.avro.Top.Builder clearTopShares() {
      topShares = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Top build() {
      try {
        Top record = new Top();
        record.top = fieldSetFlags()[0] ? this.top : (java.lang.Integer) defaultValue(fields()[0]);
        record.topShares = fieldSetFlags()[1] ? this.topShares : (java.util.List<com.yadlings.avro.StockVolume>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Top>
    WRITER$ = (org.apache.avro.io.DatumWriter<Top>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Top>
    READER$ = (org.apache.avro.io.DatumReader<Top>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.top);

    long size0 = this.topShares.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.yadlings.avro.StockVolume e0: this.topShares) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.top = in.readInt();

      long size0 = in.readArrayStart();
      java.util.List<com.yadlings.avro.StockVolume> a0 = this.topShares;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.yadlings.avro.StockVolume>((int)size0, SCHEMA$.getField("topShares").schema());
        this.topShares = a0;
      } else a0.clear();
      SpecificData.Array<com.yadlings.avro.StockVolume> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.yadlings.avro.StockVolume>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.yadlings.avro.StockVolume e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.yadlings.avro.StockVolume();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.top = in.readInt();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.yadlings.avro.StockVolume> a0 = this.topShares;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.yadlings.avro.StockVolume>((int)size0, SCHEMA$.getField("topShares").schema());
            this.topShares = a0;
          } else a0.clear();
          SpecificData.Array<com.yadlings.avro.StockVolume> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.yadlings.avro.StockVolume>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.yadlings.avro.StockVolume e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.yadlings.avro.StockVolume();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










